### ISSUE TITLE
show network when you display contract 

### ISSUE THREAD

**Issue by austintgriffith** [BuidlGuidl/hacker-houses-streams#24]
<img width="350" alt="image" src="https://github.com/BuidlGuidl/hacker-houses-streams/assets/2653167/9b0663c3-0a2d-4f05-8ed2-0547e84d5509">

^ put the network in here

---

<img width="198" alt="image" src="https://github.com/BuidlGuidl/hacker-houses-streams/assets/2653167/774cfa11-e698-4ef0-8735-93d04f3745f1">

like it is here ^

**Comment by Pabl0cks** [comment]
👌 Adding it
