### ISSUE TITLE
Show "Updated" activity from Github on the project page

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/hacker-houses-streams#8]
Next to the project title, show an "Updated X minutes ago" text. We need to fetch that info from the Github.

"carlos-sand-garden" branch

![image](https://github.com/BuidlGuidl/hacker-houses-streams/assets/2486142/7c394b58-708b-4698-a411-407f9d55bd2f)

Similar as what GH does:

![image](https://github.com/BuidlGuidl/hacker-houses-streams/assets/2486142/77a295d1-cf1b-4712-9f8c-a5664ae0a509)

**Comment by damianmarti** [comment]
@carletex what do you mean by "Updated X minutes ago". Does it mean an update on the main branch or on any branch?

**Comment by damianmarti** [comment]
@carletex do you have any preference about what lib to use for the "date to text" stuff, like "Updated yesterday", or maybe if we are using a library for this on another project, we can use the same...

**Comment by carletex** [comment]
@damianmarti 

> Does it mean an update on the main branch or on any branch?

I'd say any update to the project, to any branch!

> do you have any preference about what lib to use for the "date to text" stuff, like "Updated yesterday", or maybe if we are using a library for this on another project, we can use the same...

In SpeedRunEthereum, we use the library [moment](https://www.npmjs.com/package/moment). I don't feel super strong about it, but I think it could be a nice option!!

![image](https://github.com/BuidlGuidl/hacker-houses-streams/assets/2486142/16bf208a-7b9a-4616-91f0-86ac660ad51c)


![image](https://github.com/BuidlGuidl/hacker-houses-streams/assets/2486142/d8e34797-f851-4a4c-8876-04d2a967c118)

Thanks Damu!!!
